# Generated by Django 4.1.3 on 2023-01-21 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
