# Generated by Django 4.1.3 on 2023-01-21 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_cartitem_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='item',
            new_name='product',
        ),
    ]
